// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phdzvdzzgmzejpznfjqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoZHp2ZHp6Z216ZWpwem5manF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODkzNzAsImV4cCI6MjA2Njc2NTM3MH0.IL7HBA8GidLvwg3HXlUJKU4M-tMRJsD5oCxsYWO73gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);